language: python

python:
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest
  - pip install pytest-cov
  - pip install coverage
  - pip install codecov

script:
  - python -m pytest tests --cov=. 

after_success:
- coveralls
- codecov # submit coverage

addons:
  chrome: stable