language: python

python:
  - "3.8"

dist: xenial
sudo: required
services:
  - xvfb

addons:
  chrome: stable
  sauce_connect:
    username: "oauth-dkaggulire-e89a1"
    access_key: "976e4359-704a-4799-a9ed-3d2c2b6d802a"

before_script:
  - export DISPLAY=:99.0

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest
  - pip install pytest-cov
  - pip install coverage
  - pip install codecov

script:
  - python -m pytest tests --cov=. 

after_success:
- coveralls
- codecov # submit coverage