language: python

python:
  - "3.8"

dist: xenial
sudo: required
services:
  - xvfb

addons:
  chrome: stable
  

before_script:
  - export DISPLAY=:99.0
  - echo $TRAVIS_BUILD_DIR
  - mkdir $HOME/Desktop/scrapping/
  - touch companies.txt
  - echo UEGCL > companies.txt
  - echo Kanzucode > companies.txt
  - echo Bell > companies.txt
  - echo NBS > companies.txt
  - echo Bukedde > companies.txt
  - echo Grammarly > companies.txt
  - echo NewVision > companies.txt
  - echo Monitor > companies.txt
  - echo Linkedin > companies.txt
  - echo Sony > companies.txt
  - sudo apt-get install unzip
  - wget -N https://chromedriver.storage.googleapis.com/93.0.4577.63/chromedriver_linux64.zip -P ~/Downloads
  - unzip ~/Downloads/chromedriver_linux64.zip -d ~/Downloads
  - sudo mv -f ~/Downloads/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest
  - pip install pytest-cov
  - pip install coverage
  - pip install codecov

script:
  - python -m pytest tests --cov=. 

after_success:
- coveralls
- codecov # submit coverage