language: python

dist: xenial
sudo: required
services:
  - xvfb

addons:
  chrome: stable
  sauce_connect:
    username: "oauth-dkaggulire-e89a1"
    access_key: "976e4359-704a-4799-a9ed-3d2c2b6d802a"

python:
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest
  - pip install pytest-cov
  - pip install coverage
  - pip install codecov

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - rackup  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc

script:
  - python -m pytest tests --cov=. 

after_success:
- coveralls
- codecov # submit coverage

